### PR TITLE
Building HSAIL

### PR DESCRIPTION
**Pull request by aditya4d**
This change will build HSAIL backend. And be able to run automated tests

### CODE REVIEW

**Comment by arsenm** [comment]
HSAIL is intentionally missing from this list. You should enable it with -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=HSAIL

**Comment by aditya4d** [comment]
I wonder why that way?

**Comment by arsenm** [comment]
New targets upstream start out as experimental and not built by default

**Comment by aditya4d** [comment]
Oh. Is it an LLVM community rule?

**Pull request closed without merging**
